### ISSUE TITLE
NPE trying to index

### ISSUE THREAD

**Issue by dmnt3rr0r** [BayanGroup/nutch-custom-search#15]
I am trying to use extractor as a html/index filter but I am getting a NPE when its trying to load the config file despite the fact that I have an extractors.xml file in the conf directory. Here is the exact error:

java.lang.NullPointerException
        at ir.co.bayan.simorq.zal.extractor.nutch.ExtractorIndexingFilter.filter(ExtractorIndexingFilter.java:71)
        at org.apache.nutch.indexer.IndexingFilters.filter(IndexingFilters.java:50)
        at org.apache.nutch.indexer.IndexerMapReduce.reduce(IndexerMapReduce.java:291)
        at org.apache.nutch.indexer.IndexerMapReduce.reduce(IndexerMapReduce.java:53)
        at org.apache.hadoop.mapred.ReduceTask.runOldReducer(ReduceTask.java:522)
        at org.apache.hadoop.mapred.ReduceTask.run(ReduceTask.java:421)
        at org.apache.hadoop.mapred.LocalJobRunner$Job.run(LocalJobRunner.java:398)

Any thoughts about what is going on?

**Comment by tahagh** [comment]
Something has prevented your config file to be loaded. My first guess is that there might be some syntax errors in your extractors.xml file. Is there any error report in your nutch log file regarding this ?

**Comment by dmnt3rr0r** [comment]
Sorry, I didn't bother looking up 20 lines in the log. Thanks!
