### ISSUE TITLE
Unlike in all examples, I am asked to explicitly declare a "url" field in my extractors.xml where I want to use fragments

### ISSUE THREAD

**Issue by manjunathbharadwaj** [BayanGroup/nutch-custom-search#25]
Here is my extractors.xml

<config xmlns="http://bayan.ir" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://bayan.ir https://raw.githubusercontent.com/BayanGroup/nutch-custom-search/master/zal.extractor.core/src/main/resources/extractors.xsd">

    <fields>
        <field name="SellerPhone" multi="true" />
    </fields>
    <documents>
        <document url="." engine="css" >

    <fragment root=".biz-card-content">
      <extract-to field="SellerPhone">
                <constant value="tools" />
      </extract-to>
      <extract-to field="url">
            <first>
                <attribute name="href">
                    <expr value="a"/>
                 </attribute>
            </first>
      </extract-to>
    </fragment>

        </document>
    </documents>
</config>

Logs:
2015-05-20 04:18:50,550 DEBUG util.ObjectCache - No object cache found for conf=Configuration: core-default.xml, core-site.xml, nutch-default.xml, nutch-site.xml, instantiating a new object cache
2015-05-20 04:18:52,212 ERROR nutch.ExtractorParseFilter -
javax.xml.bind.UnmarshalException
 \- with linked exception:
[org.xml.sax.SAXParseException; lineNumber: 27; columnNumber: 10; cvc-id.1: There is no ID/IDREF binding for IDREF 'url'.]
        at javax.xml.bind.helpers.AbstractUnmarshallerImpl.createUnmarshalException(AbstractUnmarshallerImpl.java:335)
        at com.sun.xml.bind.v2.runtime.unmarshaller.UnmarshallerImpl.createUnmarshalException(UnmarshallerImpl.java:523)
        at com.sun.xml.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal0(UnmarshallerImpl.java:220)
        at com.sun.xml.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal(UnmarshallerImpl.java:189)

I can add a field "url" in the \<fields\> part of my xml and make this go away, but none of the examples in the package have this. Why is this happening? What additional details can I provide?

**Comment by tahagh** [comment]
Every field you are referring to in an extract-to rule, must be defined in the fields section, including the url field so you are doing the right thing. 
The examples do the same, if they needed, for instance [this](https://github.com/BayanGroup/nutch-custom-search/blob/master/zal.extractor.core/src/test/resources/extractors-css-test-multi.xml) which declares url field.

**Comment by manjunathbharadwaj** [comment]
Thanks, that works.
